// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsVi9aubBdYcml-gsrpiA6hjrs2u5cxKc',
    appId: '1:603925997351:web:fca2af05eff9a8d8e5ab02',
    messagingSenderId: '603925997351',
    projectId: 'ahorramax-a2720',
    authDomain: 'ahorramax-a2720.firebaseapp.com',
    storageBucket: 'ahorramax-a2720.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxvGVq8dOtEcWGR-5jPpyEW51MgT1NS4Q',
    appId: '1:603925997351:android:de51fad92f4e6aa2e5ab02',
    messagingSenderId: '603925997351',
    projectId: 'ahorramax-a2720',
    storageBucket: 'ahorramax-a2720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-KfTc2vMoS4yXmYw_71RgbMuTHaWQah0',
    appId: '1:603925997351:ios:3bb938a882bd2dfee5ab02',
    messagingSenderId: '603925997351',
    projectId: 'ahorramax-a2720',
    storageBucket: 'ahorramax-a2720.firebasestorage.app',
    iosBundleId: 'com.example.ahorramax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-KfTc2vMoS4yXmYw_71RgbMuTHaWQah0',
    appId: '1:603925997351:ios:3bb938a882bd2dfee5ab02',
    messagingSenderId: '603925997351',
    projectId: 'ahorramax-a2720',
    storageBucket: 'ahorramax-a2720.firebasestorage.app',
    iosBundleId: 'com.example.ahorramax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsVi9aubBdYcml-gsrpiA6hjrs2u5cxKc',
    appId: '1:603925997351:web:b25d9a4e4689b3f7e5ab02',
    messagingSenderId: '603925997351',
    projectId: 'ahorramax-a2720',
    authDomain: 'ahorramax-a2720.firebaseapp.com',
    storageBucket: 'ahorramax-a2720.firebasestorage.app',
  );

}